apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-demo
spec:
  selector:
    matchLabels:
      app: kubernetes-demo
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: kubernetes-demo
    spec:
      containers:
      - name: kubernetes-demo
        image: nam908/java-springboot
      